FROM openjdk:8-jre

ENV ES_PKG_NAME elasticsearch-1.3.9
ENV PLUGIN_KOPF_VERSION 1.6.2

RUN \
  cd / && \
  wget -nv https://download.elasticsearch.org/elasticsearch/elasticsearch/$ES_PKG_NAME.tar.gz && \
  tar xvzf $ES_PKG_NAME.tar.gz && \
  rm -f $ES_PKG_NAME.tar.gz && \
  mv /$ES_PKG_NAME /elasticsearch

WORKDIR /elasticsearch/plugins/kopf
RUN \
  wget -nv https://github.com/lmenezes/elasticsearch-kopf/archive/v$PLUGIN_KOPF_VERSION.tar.gz \
       -O elasticsearch-kopf-$PLUGIN_KOPF_VERSION.tar.gz && \
  tar xvzf elasticsearch-kopf-$PLUGIN_KOPF_VERSION.tar.gz && \
  rm elasticsearch-kopf-$PLUGIN_KOPF_VERSION.tar.gz && \
  mv elasticsearch-kopf-$PLUGIN_KOPF_VERSION kopf

VOLUME ["/elasticsearch/data"]

CMD ["/elasticsearch/bin/elasticsearch"]

EXPOSE 9200
EXPOSE 9300
