version: '2'

services:
    elasticsearch:
        build:
            context: .
            dockerfile: Dockerfile-Elasticsearch-1.3.9
        image: elasticsearch:1.3.9
        volumes:
            - elasticsearch:/elasticsearch/data
        ports:
            - "4712:9200"
        networks:
            - backend
            - kitodopublication_frontend
        depends_on:
            - fcrepo
        environment:
            WAIT_HOSTS: fcrepo:8080, fcrepo:61616

    fcrepo:
        build:
            context: .
            dockerfile: Dockerfile-Qucosa-Fcrepo3
            args:
                fcrepo_version: 3.8.1
        image: qucosa-fcrepo:3.8.1
        volumes:
            - fcrepo3:/fcrepo3/data
        ports:
            - "4711:8080"
        networks:
            - backend
            - kitodopublication_frontend

volumes:
    elasticsearch:
    fcrepo3:

networks:
    backend:
    kitodopublication_frontend:
        external: true
