version: '2'

services:
    elasticsearch:
        build:
            context: .
            dockerfile: Dockerfile-Elasticsearch-1.3.9
        image: elasticsearch:1.3.9
        hostname: elasticsearch
        volumes:
            - elasticsearch:/elasticsearch/data
        ports:
            - "4712:9200"
            - "4713:9300"

    fcrepo:
        build:
            context: .
            dockerfile: Dockerfile-Qucosa-Fcrepo3
            args:
                fcrepo_version: 3.8.1
        image: qucosa-fcrepo:3.8.1
        hostname: fcrepo3
        volumes:
            - fcrepo3:/fcrepo3/data
        ports:
            - "4711:8080"
        networks:
            - default
            - kitodopublication_default
        external_links:
            - kitodopublication_typo3-app_1:typo3

volumes:
    elasticsearch:
    fcrepo3:

networks:
    kitodopublication_default:
        external: true
